Fix #62
jamf/PPPC-Utility pull request #77
Opened 2020-09-17 21:29 UTC by ty-wilson

Changed default value for Apple Event Rules when added to be true instead of false
Fix #62

2020-09-23 12:55 UTC, watkyn approved these changes

2020-09-29 07:13 UTC, kkot approved these changes

2020-09-29 14:46 UTC, watkyn requested changes
We just merged in a change log file. @ty-wilson can you merge from master and then update the change now to describe this change? Thanks

2020-10-01 16:43 UTC, ty-wilson commented
Hey @watkyn, I merged from master and it looks like that is reflected here. Let me know if that looks correct!

2020-10-01 18:25 UTC, watkyn approved these changes

2020-10-01 18:25 UTC, merged